apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wqpz585ji-python 
  janus-idp.io/tekton: wqpz585ji-python
  backstage.io/kubernetes-id: wqpz585ji-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wqpz585ji-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  