apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wqpz585ji-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wqpz585ji-python 
  name: wqpz585ji-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wqpz585ji-python 
